version: '3.8'
services:
  paper-server:
    image: ${DOCKER_IMAGE}
    container_name: paper-server
    restart: unless-stopped
    env_file:
      - /etc/deepknow.env
    ports:
      - "8002:8002"
      - "20882:20882"
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      SERVER_PORT: 8002
      SPRING_PROFILES_ACTIVE: "prod"
      DUBBO_IP_TO_REGISTRY: ${SERVICE_IP}
    volumes:
      - ./logs:/root/logs